ImageGallery/Controllers/DownloadFileController.cs
using ImageGallery.Models.DAL;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ImageGallery.Controllers
{
    public class DownloadFileController : Controller
    {  
        [OutputCache(Duration = 60, Location = OutputCacheLocation.Any, VaryByParam = "Id;t")]
        public ActionResult GetImage(int Id = 0, int t = 0)
        {
            if (Id == 0)
            {
                return File("~/images/NoImage.png", "image/png");
            }

            ImageGalleryEntities db = new ImageGalleryEntities();

            var model = db.WebFiles.Find(Id);

            if (model != null)
            {
                if (t != 0)
                {
                    byte[] img = getThumbNail(model.Data, t);
                    return File(img, model.ContentType, "thumb_" + model.FileName);
                }

                return File(model.Data, model.ContentType, model.FileName);
            }
            else
            {
                return HttpNotFound();
            }
        }

        private byte[] getThumbNail(byte[] data, int multi = 1)
        {
            using (var file = new MemoryStream(data))
            {
                int width = 200 * multi; 
                using (var image = Image.FromStream(file, true, true)) /* Creates Image from specified data stream */
                {
                    int X = image.Width;
                    int Y = image.Height;
                    int height = (int)((width * Y) / X);

                    using (var thumb = image.GetThumbnailImage(width, height, () => false, IntPtr.Zero))
                    {
                        var jpgInfo = ImageCodecInfo.GetImageEncoders().Where(codecInfo => codecInfo.MimeType == "image/png").First(); /* Returns array of image encoder objects built into GDI+ */
                        using (var encParams = new EncoderParameters(1))
                        {
                            using (var samllfile = new MemoryStream())
                            {
                                long quality = 100;
                                encParams.Param[0] = new EncoderParameter(Encoder.Quality, quality);
                                thumb.Save(samllfile, jpgInfo, encParams);
                                return samllfile.ToArray();
                            }
                        };
                    };
                };
            };
        }
    }
}

ImageGallery/Controllers/GalleryAdminController.cs
using ImageGallery.Models.DAL;
using ImageGallery.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageGallery.Controllers
{
    public class GalleryAdminController : Controller
    {
        // GET: GalleryAdmin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            ImageEditorViewModel vm = new ImageEditorViewModel();
            ViewBag.Action = "Create";
            return PartialView(vm);
        }

        [HttpPost]
        public ActionResult Create(ImageEditorViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ImageGalleryEntities db = new ImageGalleryEntities(); 

                    var fileModel = WebFileViewModel.getEntityModel(model.FileImage);
                    db.WebFiles.Add(fileModel);
                    db.SaveChanges();

                    var entity = ImageEditorViewModel.getEnityModel(model);                  
                    entity.WebImageId = fileModel.Id;
                    

                    entity.OrderNo = db.Galleries.Count() > 0 ? db.Galleries.Max(x=> x.OrderNo) + 1 : 1;
                    
                    db.Galleries.Add(entity);
                    db.SaveChanges();

                    return Json(new { success = true, Caption = model.Caption });
                }

                return Json(new { success = false, ValidationMessage = "Please check validation messages" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, ExceptionMessage = "Some error here" });
            }
        }

        public ActionResult _List()
        {
            ImageGalleryEntities db = new ImageGalleryEntities();
            var list = db.Galleries.OrderBy(x => x.OrderNo)
                        .Select(x => new ImageList
                        {
                            Id = x.Id,
                            IsActive = x.IsActive,
                            OrderNo = x.OrderNo,
                            WebImageId = x.WebImageId,
                            Title = x.Title,
                            Details=x.Details,
                            Make=x.Make,
                            Modal = x.Modal,
                            Registration =x.Registration,
                            Location =x.Location,
                            DateAndTime = x.DateAndTime,
                            
                        }).ToList();

            return PartialView(list);
        }
        

        [HttpPost]
        public JsonResult ChangeActive(int Id, bool status)
        {
            ImageGalleryEntities db = new ImageGalleryEntities();
            var entity = db.Galleries.Find(Id);
            entity.IsActive = status;
            db.SaveChanges();

            return Json(entity.Title);
        }
    }
}

ImageGallery/Views/GalleryAdmin/Create.cshtml
@model ImageGallery.ViewModel.ImageEditorViewModel

@using (Html.BeginForm("Create", "GalleryAdmin", FormMethod.Post, new { enctype = "multipart/form-data", Id="frmAddImage" }))
{
    <div class="form-horizontal">
        <h4>LogHere</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Caption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Caption, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Caption, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.Modal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Modal, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Modal, "", new { @class = "text-danger" })
        </div>
            @Html.LabelFor(model => model.Registration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Registration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Registration, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.DateAndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAndTime, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.Details, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
        </div>
    </div>


        <div class="form-group">
            <div class="col-md-2">
                <label class="pull-right">  Image:</label>
            </div>
            <div class="col-md-9">
                @Html.TextBoxFor(m => m.FileImage, new { type = "file" })
                @Html.ValidationMessageFor(model => model.FileImage, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnAddImage" value="Create" class="btn btn-primary" />
            </div>
          
        </div> 
    </div>
}



@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">

    $(function () {
        $("#btnAddImage").on("click", function (e) {
            var $form = $("#frmAddImage");
            $form.validate();
            if (!$form.valid()) {
                return false;
            }

            e.preventDefault();
            var formData = new FormData();
            var data = $form.find(':input[name]:not(:disabled)').filter(':not(:checkbox), :checked').map(function () {
                var input = $(this);

                if (input.attr('type') == "file") {

                    formData.append(input.attr('name'), input[0].files[0]);
                    return {
                        name: input.attr('name'),
                        value: input[0].files[0]
                    };
                } else {
                    formData.append(input.attr('name'), input.val());
                    return {
                        name: input.attr('name'),
                        value: input.val()
                    };
                }
            }).get();
            debugger;
            $.ajax({
                url: '/GalleryAdmin/Create',
                data: formData,
                type: "POST",
                contentType: false,
                processData: false,
                success: function (data, textStatus, jqXHR) { 
                    if (data.success == true) {
                        $("#successmessage").html(data.Caption + " has been added successfully").show().delay(5000).fadeOut();
                        $("#ListPanel").load($("#ListPanel").data("url"));
                        $("#ImagePanel").load($("#ImagePanel").data("url"));
                        return true;
                    }
                    if (data.ExceptionMessage) {
                        $("#errormessage").html(data.ExceptionMessage).show().delay(5000).fadeOut();
                        return false;
                    }
                    if (data.ValidationMessage) {
                        $("#errormessage").html(data.ExceptionMessage).show().delay(5000).fadeOut();
                        return false;
                    }
                    return false;
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#errormessage").html(textStatus).show().delay(5000).fadeOut();
                },
                complete: function (jqXHR, textStatus) {
                }
            });

        });
    });
</script>

ImageGallery/Views/GalleryAdmin/Index.cshtml
@{
    ViewBag.Title = "User Admin";}


<div id="ImagePanel" data-url="@Url.Action("Create")">
    @Html.Action("Create")
</div>
<div class="row">
    <div class="col-md-offset-2 col-md-10">
        <div class="alert alert-danger" style="display:none" role="alert" id="errormessage"></div>
        <div class="alert alert-success" style="display:none" role="alert" id="successmessage"></div>
    </div>
</div>
<hr />
<div id="ListPanel" data-url="@Url.Action("_List")">
    @Html.Action("_List")
</div>

ImageGallery/Views/GalleryAdmin/_List.cshtml
@model IEnumerable<ImageGallery.ViewModel.ImageList>

<ul style="list-style:none;" class="row">
    @foreach (var item in Model)
    {
        <li class="col-md-3">
            <br />
            <img class="img" src="@Url.Action("GetImage", "DownloadFile", new { Area ="" , Id= item.WebImageId, t =2 })" style="width:100%;height:180px;" />
            <br />
            <label>@item.Title</label>
            <br />
            <br />
        </li>
    }
</ul>